// Boards
export const FETCH_BOARDS_REQUEST = 'FETCH_BOARDS_REQUEST';
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_FAILURE = 'FETCH_BOARDS_FAILURE';
export const CREATE_BOARD_REQUEST = 'CREATE_BOARD_REQUEST';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE';

// Board Details
export const FETCH_BOARD_REQUEST = 'FETCH_BOARD_REQUEST';
export const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
export const FETCH_BOARD_FAILURE = 'FETCH_BOARD_FAILURE';

// Lists
export const FETCH_LISTS_REQUEST = 'FETCH_LISTS_REQUEST';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE';
export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';
export const ARCHIVE_LIST_REQUEST = 'ARCHIVE_LIST_REQUEST';
export const ARCHIVE_LIST_SUCCESS = 'ARCHIVE_LIST_SUCCESS';
export const ARCHIVE_LIST_FAILURE = 'ARCHIVE_LIST_FAILURE';

// Cards
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const CREATE_CARD_REQUEST = 'CREATE_CARD_REQUEST';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAILURE = 'CREATE_CARD_FAILURE';
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';

// Checklists
export const FETCH_CHECKLISTS_REQUEST = 'FETCH_CHECKLISTS_REQUEST';
export const FETCH_CHECKLISTS_SUCCESS = 'FETCH_CHECKLISTS_SUCCESS';
export const FETCH_CHECKLISTS_FAILURE = 'FETCH_CHECKLISTS_FAILURE';
export const CREATE_CHECKLIST_REQUEST = 'CREATE_CHECKLIST_REQUEST';
export const CREATE_CHECKLIST_SUCCESS = 'CREATE_CHECKLIST_SUCCESS';
export const CREATE_CHECKLIST_FAILURE = 'CREATE_CHECKLIST_FAILURE';
export const DELETE_CHECKLIST_REQUEST = 'DELETE_CHECKLIST_REQUEST';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAILURE = 'DELETE_CHECKLIST_FAILURE';

// CheckItems
export const CREATE_CHECKITEM_REQUEST = 'CREATE_CHECKITEM_REQUEST';
export const CREATE_CHECKITEM_SUCCESS = 'CREATE_CHECKITEM_SUCCESS';
export const CREATE_CHECKITEM_FAILURE = 'CREATE_CHECKITEM_FAILURE';
export const DELETE_CHECKITEM_REQUEST = 'DELETE_CHECKITEM_REQUEST';
export const DELETE_CHECKITEM_SUCCESS = 'DELETE_CHECKITEM_SUCCESS';
export const DELETE_CHECKITEM_FAILURE = 'DELETE_CHECKITEM_FAILURE';
export const TOGGLE_CHECKITEM_REQUEST = 'TOGGLE_CHECKITEM_REQUEST';
export const TOGGLE_CHECKITEM_SUCCESS = 'TOGGLE_CHECKITEM_SUCCESS';
export const TOGGLE_CHECKITEM_FAILURE = 'TOGGLE_CHECKITEM_FAILURE';